# Generated by Django 3.1.6 on 2021-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='course/images')),
                ('level', models.CharField(choices=[('beg', 'Beginner'), ('int', 'Intermediat'), ('adv', 'Advance')], max_length=5)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('status', models.CharField(choices=[('drf', 'Draft'), ('pub', 'Published')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
