# Generated by Django 3.1.6 on 2021-03-04 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='static/course/images/')),
                ('level', models.CharField(choices=[('beg', 'Beginner'), ('int', 'Intermediat'), ('adv', 'Advance')], max_length=5)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('drf', 'Draft'), ('pub', 'Published')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ManyToManyField(to='session.Session')),
                ('students', models.ManyToManyField(related_name='Student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
