# Generated by Django 3.1.6 on 2021-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('course', '0003_auto_20210225_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session',
            field=models.ManyToManyField(default='', null=True, to='session.Session'),
        ),
    ]
