# Generated by Django 3.1.6 on 2021-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_course'),
        ('course', '0005_auto_20210312_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
