# Generated by Django 3.1.6 on 2021-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('course', '0005_auto_20210225_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session',
            field=models.ManyToManyField(default='', to='session.Session'),
        ),
    ]
