# Generated by Django 3.1.6 on 2021-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
    ]
