# Generated by Django 3.1.7 on 2021-06-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_remove_session_course'),
        ('course', '0010_auto_20210519_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='session.session'),
        ),
    ]
