# Generated by Django 3.1.7 on 2021-06-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_remove_session_course'),
        ('course', '0011_course_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session'),
        ),
    ]
