# Generated by Django 3.1.7 on 2021-06-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210614_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
    ]
