# Generated by Django 3.1.7 on 2021-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0017_remove_session_course'),
        ('course', '0013_remove_course_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ManyToManyField(to='session.Session'),
        ),
    ]
