# Generated by Django 3.1.7 on 2021-06-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
    ]
