# Generated by Django 3.1.7 on 2021-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_account_courses'),
        ('course', '0020_remove_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(to='user.Account'),
        ),
    ]
