# Generated by Django 3.1.7 on 2021-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_account_courses'),
        ('course', '0021_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(related_name='instructor', to='user.Account'),
        ),
    ]
