# Generated by Django 3.1.7 on 2021-06-16 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0022_auto_20210616_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
