# Generated by Django 3.1.7 on 2021-06-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20210616_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
