# Generated by Django 3.1.6 on 2021-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DurationField(),
        ),
    ]
