# Generated by Django 3.1.6 on 2021-03-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_remove_session_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='session',
            managers=[
            ],
        ),
    ]
