# Generated by Django 3.1.7 on 2021-05-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20210311_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='video',
            field=models.FileField(upload_to='media/session/videos'),
        ),
    ]
