# Generated by Django 3.1.7 on 2021-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_auto_20210519_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='session',
            name='video',
            field=models.FileField(upload_to='sessions/videos'),
        ),
    ]
