# Generated by Django 3.1.7 on 2021-06-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_auto_20210614_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
    ]
