# Generated by Django 3.1.7 on 2021-06-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_auto_20210614_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
    ]
