# Generated by Django 3.1.7 on 2021-06-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_course_session'),
        ('session', '0019_auto_20210614_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course'),
        ),
    ]
