# Generated by Django 3.1.6 on 2021-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
    ]
