# Generated by Django 3.1.6 on 2021-03-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
