# Generated by Django 3.1.7 on 2021-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='account/images/user.png', null=True, upload_to='account/images'),
        ),
    ]
