# Generated by Django 3.1.7 on 2021-06-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_remove_course_instructor'),
        ('user', '0004_remove_account_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
