# Generated by Django 3.1.7 on 2021-06-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_account_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='courses',
        ),
    ]
